# Utiliser une image officielle Python en version slim
FROM python:3.9-slim

# Définir le répertoire de travail dans le container
WORKDIR /app

# Copier les fichiers nécessaires
COPY requirements.txt ./
COPY app.py ./

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port de l’application
EXPOSE 5000

# Commande pour lancer l’application
CMD ["python", "app.py"]
